### ISSUE TITLE
Linting and formatting

### ISSUE THREAD

**Issue by langston-barrett** [JackMiranda/herms#63]
The following tools, integrated into the Travis build, can lead to significant gains in code quality:
 - hindent
 - hlint
 - `GHC-Options: -Werror` with selective warnings turned on

What do you think about enabling a few of these? Stylistic checks [shouldn't be enabled in all builds](https://www.snoyman.com/blog/2017/11/future-proofing-test-suites), but having them on in CI can be pretty beneficial. 

See also https://taylor.fausak.me/2014/03/04/haskeleton-a-haskell-project-skeleton/#code-quality

**Comment by JackKiefer** [comment]
I really like the idea of it! It'd actually be pretty apt to do something like this right now since I somehow just mucked up the Travis build (Herm's still builds fine; it's just something with Travis). 

I'm a bit too slammed over the next few days to work on Herm's, but I'll happily approve any pull requests. :)

Unrelated, but I'm excited to tell someone: I'm also working on a feature to parse a simple markdown-ish file to add a recipe instead of going through the interactive menu!

**Comment by siddharthist** [comment]
Nice! That sounds really useful. I would suggest using a standard file format like TOML or YAML for interoperability (and to eliminate custom parsing code).

I'm working on this issue now.

**Comment by siddharthist** [comment]
Unfortunately, I can't use the same script that was used to originally generate the `.travis.yml`: https://github.com/haskell-CI/haskell-ci/issues/155

**Comment by siddharthist** [comment]
Though my CI build is working: https://travis-ci.org/siddharthist/herms/jobs/404012180. Perhaps it was an intermittent issue?

**Comment by siddharthist** [comment]
At some point, we may also want to consider Brittany instead of `hindent`. But it's pretty new, and has no package available via `apt-get`. https://www.reddit.com/r/haskell/comments/8x0x77/brittany_vs_hindent_vs_stylishhaskell/

**Comment by langston-barrett** [comment]
We use hlint now (#66), and haskell-ci doesn't yet support using formatters like brittany or hindent. I personally wouldn't want to go back to manually configuring Travis, so let's close this for now.

Of course, I would still welcome PRs/re-opening this if there is interest!
